---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: notify
    type: slack-notification
    icon: slack
    source:
      url: ((slack-webhook))

  - name: fauna-js-repository
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-js.git
      branch: main
      private_key: ((github-ssh-key))

  - name: testtools
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/testools.git
      branch: main
      private_key: ((github-ssh-key))

groups:
  - name: standard-release
    jobs:
      - set-self
      - validate
      - release

jobs:
  - name: set-self
    serial: true
    plan:
      - get: fauna-js-repository
        trigger: true
      - set_pipeline: self
        file: fauna-js-repository/concourse/pipeline.yml

  - name: validate
    serial: true
    public: false
    plan:
      - get: fauna-js-repository
        trigger: true
        passed:
          - set-self

      - get: testtools

      - task: integration-tests
        file: fauna-js-repository/concourse/tasks/integration-tests.yml
        privileged: true

      - task: runtime-validation
        file: fauna-js-repository/concourse/tasks/runtime-validation.yml
        params:
          AWS_LAMBDA_ROLE_ARN: arn:aws:iam::424964496154:role/driver-test-lambda-role-0cc3197
          AWS_ACCESS_KEY_ID: ((runtime-validation-aws.aws-access-key-id.value))
          AWS_SECRET_ACCESS_KEY: ((runtime-validation-aws.aws-secret-key.value))
          CLOUDFLARE_API_TOKEN: ((runtime-validation.CLOUDFLARE_API_TOKEN))
          FAUNA_SECRET: ((runtime-validation.FAUNA_SECRET))
          NETLIFY_ACCOUNT: ((runtime-validation.NETLIFY_ACCOUNT))
          NETLIFY_AUTH_TOKEN: ((runtime-validation.NETLIFY_AUTH_TOKEN))
          VERCEL_TOKEN: ((runtime-validation.VERCEL_TOKEN))
        on_success:
          put: notify
          params:
            text: "attention haters: fauna-js driver release passed integration tests"
        on_failure:
          put: notify
          params:
            text: fauna-js driver release failed integration tests

  - name: release
    serial: true
    public: false
    plan:
      - get: fauna-js-repository
        trigger: false
        passed:
          - validate

      - task: publish
        file: fauna-js-repository/concourse/tasks/npm-publish.yml
        params:
          NPM_TOKEN: ((npm_token))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish
        on_failure:
          put: notify
          params:
            text_file: slack-message/publish
